language: cpp
sudo: required
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/.cache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - environment-modules
      - lcov

env:
  global:
    - SPACK_ROOT: $HOME/.cache/spack
    - PATH: $PATH:$HOME/.cache/spack/bin

before_install:
  - export CXX=g++-7
  - export CC=gcc-7
  - export FC=gfortran-7
  - export CXXFLAGS="-coverage"
  - alias gcov=gcov-7

install:
  - if ! which spack >/dev/null; then
      mkdir -p $SPACK_ROOT &&
      git clone --depth 50 https://github.com/spack/spack.git $SPACK_ROOT &&
      echo -e "config:""\n  build_jobs:"" 2" > $SPACK_ROOT/etc/spack/config.yaml;
    fi
  - spack repo add $(echo ${TRAVIS_BUILD_DIR})/scripts/spack-repo
  - spack clean -a
  - source /etc/profile &&
    source $SPACK_ROOT/share/spack/setup-env.sh
  - spack load cmake googletest
  
script:
  - mkdir -p $HOME/build
  - cd $HOME/build
  - spack setup splinelib@github
  - ./spconfig.py $TRAVIS_BUILD_DIR
  - make VERBOSE=on -j 2
  - ./test/SplineLibTests
  - ls -la
  - ls -la ./test

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -la
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
