language: cpp
sudo: required
dist: trusty

services:
  - docker

stages:
  - AcceptanceTests
#  - UnitTests
#  - Lint
#  - Install

jobs:
  include:
#
#    - stage: UnitTests
#      name: GCC 7 - Release
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelibtests:gcc7 -f scripts/docker/Dockerfile.test.gcc7.release .
#      script: docker run -te "TERM=xterm-256color" --name tests_gcc7 splinelibtests:gcc7
#      after_success: docker rm tests_gcc7
#    - stage: UnitTests
#      name: GCC 7 - Debug
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelibtests:gcc7 -f scripts/docker/Dockerfile.test.gcc7.debug .
#      script: docker run -te "TERM=xterm-256color" --name tests_gcc7 splinelibtests:gcc7
#      after_success: docker rm tests_gcc7
#    - stage: UnitTests
#      name: GCC 8 - Release
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelibtests:gcc8 -f scripts/docker/Dockerfile.test.gcc8.release .
#      script: docker run -te "TERM=xterm-256color" --name tests_gcc8 splinelibtests:gcc8
#      after_success: docker rm tests_gcc8
#    - stage: UnitTests
#      name: GCC 8 - Debug
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelibtests:gcc8 -f scripts/docker/Dockerfile.test.gcc8.debug .
#      script: docker run -te "TERM=xterm-256color" --name tests_gcc8 splinelibtests:gcc8
#      after_success: docker rm tests_gcc8
#    - stage: UnitTests
#      name: Clang 5 - Release
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelibtests:clang5 -f scripts/docker/Dockerfile.test.clang5.release .
#      script: docker run -te "TERM=xterm-256color" --name tests_clang5 splinelibtests:clang5
#      after_success: docker rm tests_clang5
#    - stage: UnitTests
#      name: Clang 5 - Debug
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelibtests:clang5 -f scripts/docker/Dockerfile.test.clang5.debug .
#      script: docker run -te "TERM=xterm-256color" --name tests_clang5 splinelibtests:clang5
#      after_success: docker rm tests_clang5
#    - stage: UnitTests
#      name: Clang 6 - Release
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelibtests:clang6 -f scripts/docker/Dockerfile.test.clang6.release .
#      script: docker run -te "TERM=xterm-256color" --name tests_clang6 splinelibtests:clang6
#      after_success: docker rm tests_clang6
#    - stage: UnitTests
#      name: Clang 6 - Debug
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelibtests:clang6 -f scripts/docker/Dockerfile.test.clang6.debug .
#      script: docker run -te "TERM=xterm-256color" --name tests_clang6 splinelibtests:clang6
#      after_success: docker rm tests_clang6
#
#    - stage: Lint
#      name: CppLint
#      before_install: docker pull mfcats/splinelib:spack
#      install: docker build -t splinelib:cpplint -f scripts/docker/Dockerfile.lint.cpplint .
#      script: docker run -te "TERM=xterm-256color" --name cpplint splinelib:cpplint
#      after_success: docker rm cpplint
#    - stage: Lint
#      name: Clang-Tidy
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelib:clang-tidy -f scripts/docker/Dockerfile.lint.clang-tidy .
#      script: docker run -te "TERM=xterm-256color" --name clang-tidy splinelib:clang-tidy
#      after_success: docker rm clang-tidy
#    - stage: Lint
#      name: OCLint
#      before_install: docker pull cm314/splinelib:gtest3
#      install: docker build -t splinelib:oclint -f scripts/docker/Dockerfile.lint.oclint .
#      script: docker run -te "TERM=xterm-256color" --name oclint splinelib:oclint
#      after_success: docker rm clang-tidy

    - stage: AcceptanceTests
      before_install: docker pull mfcats/splinelib:spack
      install: docker build -t splinelibtests:acceptance -f scripts/docker/Dockerfile.acceptancetests .
      script: docker run -te "TERM=xterm-256color" --name acceptance splinelibtests:acceptance
      after_success: docker rm acceptance
#
#    - stage: Install
#      before_install: docker pull mfcats/splinelib:spack
#      install: docker build -t splinelibtests:install -f scripts/docker/Dockerfile.install .
#      script: docker run -te "TERM=xterm-256color" --name install splinelibtests:install
#      after_success: docker rm install
#
