language: cpp
sudo: required
dist: trusty

services:
  - docker

stages:
  - UnitTests
  - Lint
  - AcceptanceTests
  - Install

jobs:
  include:
    - stage: UnitTests
      name: Clang 6 - Debug - with Armadillo
      install: docker build -t splinelibtests:clang6 -f scripts/docker/Dockerfile.clang6.debug.witharma .
      script: docker run -te "TERM=xterm-256color" --name tests_clang6 splinelibtests:clang6
