language: cpp
sudo: required
dist: trusty

services:
- docker

stages:
- UnitTests
- Lint
- AcceptanceTests
- Install

jobs:
  include:
  - stage: UnitTests
    name: GCC 7 - Debug
    install: docker build -t splinelibtests:gcc7 -f scripts/docker/Dockerfile.test.gcc7.debug .
    script: docker run -te "TERM=xterm-256color" --name tests_gcc7 splinelibtests:gcc7
