language: cpp
sudo: required
dist: trusty

services:
  - docker

stages:
  - prepare
  - lint
  - test
  - coverage

jobs:
  include:
    - stage: prepare
      install: docker pull mfcats/splinelib:spack
    - stage: prepare
      install: docker pull mfcats/splinelib:gtest
    - stage: lint
      name: cpplint
      install: docker build -t splinelib:cpplint -f scripts/docker/Dockerfile.lint.cpplint .
      script: docker run --name cpplint splinelib:cpplint
      after_success: docker remove cpplint
    - stage: lint
      name: clang-tidy
      install: echo lint clang-tidy install # docker build -t splinelib:clang-tidy -f scripts/docker/Dockerfile.lint.clang-tidy .
      script: echo lint clang-tidy # docker run --name clang-tidy splinelib:clang-tidy
    - stage: test
      name: gcc7
      install: docker build -t splinelibtests:gcc7 -f scripts/docker/Dockerfile.gcc7test .
      script: docker run --name tests_gcc7 splinelibtests:gcc7
      after_success: docker remove tests_gcc7
    - stage: test
      name: gcc8
      install: docker build -t splinelibtests:gcc8 -f scripts/docker/Dockerfile.gcc8test .
      script: docker run --name tests_gcc8 splinelibtests:gcc8
      after_success: docker remove tests_gcc8
    - stage: coverage
      install: echo lint coverage install # docker build -t splinelibtests:coverage -f scripts/docker/Dockerfile.coverage .
      script: echo coverage # docker run --name coverage splinelibtests:coverage
      after_success: echo finish

