language: cpp
sudo: required

services:
  - docker

install:
  - docker pull cm314/splinelib:googletest_gcc8_new2
  - docker build -t splinelibtests:gcc8 -f scripts/docker/Dockerfile.gcc8test .

script:
  - docker run --name tests_gcc8 splinelibtests:gcc8
  - docker rm tests_gcc8

after_success:
  - cpplint ${TRAVIS_BUILD_DIR}/src/*

