language: cpp
sudo: required
dist: trusty

services:
- docker

stages:
- Install

jobs:
    include:

    - stage: Install
      name: IGA
      install: docker build -t splinelibtests:install_iga -f example/iga/scripts/docker/Dockerfile.install .
      script: docker run -te "TERM=xterm-256color" --name install_iga splinelibtests:install_iga
