language: cpp
sudo: required
dist: trusty

services:
  - docker

stages:
  - lint
  - test
  - coverage

before_install:
  - docker pull mfcats/splinelib:spack
  - docker pull mfcats/splinelib:gtest

jobs:
  include:
    - stage: lint
      name: cpplint
      install: docker build -t splinelib:cpplint -f scripts/docker/Dockerfile.lint.cpplint .
      script: docker run --name cpplint splinelib:cpplint
      after_success: docker remove cpplint
    - stage: lint
      install: echo lint clang-tidy install # docker build -t splinelib:clang-tidy -f scripts/docker/Dockerfile.lint.clang-tidy .
      script: echo lint clang-tidy # docker run --name clang-tidy splinelib:clang-tidy
    - stage: test
      install: docker build -t splinelibtests:gcc7 -f scripts/docker/Dockerfile.gcc7test .
      script: docker run --name tests_gcc7 splinelibtests:gcc7
      after_success: docker remove tests_gcc7
    - stage: test
      install: docker build -t splinelibtests:gcc8 -f scripts/docker/Dockerfile.gcc8test .
      script: docker run --name tests_gcc8 splinelibtests:gcc8
      after_success: docker remove tests_gcc8
    - stage: coverage
      install: echo lint coverage install # docker build -t splinelibtests:coverage -f scripts/docker/Dockerfile.coverage .
      script: echo coverage # docker run --name coverage splinelibtests:coverage
      after_success: echo finish

