language: cpp
sudo: required

services:
  - docker

install:
  - docker pull cm314/splinelib:googletest_gcc8_new2
  - docker build -t splinelibtests:gcc8 -f scripts/docker/Dockerfile.gcc8test .

script:
  - docker run --name tests_gcc8 splinelibtests:gcc8
  - docker cp $(docker ps -qf "name=tests_gcc8"):/code/build ${TRAVIS_BUILD_DIR}
  - docker rm tests_gcc8

