FROM mfcats/splinelib:gcc8

# Add current directory as working directory to docker
ADD . /code
WORKDIR /code

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /code/bashrc2

# Prepare build
RUN /code/.cache/spack/bin/spack --version
RUN /code/.cache/spack/bin/spack repo add /code/SplineLib/scripts/spack-repo
RUN mkdir /code/build
WORKDIR /code/build
RUN /code/.cache/spack/bin/spack setup -v splinelib@github
RUN ./../spconfig.py ..

# Build and execute tests
CMD make && ./test/SplineLibTests