FROM mfcats/splinelib:gcc8

# Work in /spack
ADD . /code
WORKDIR /code

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /spack/bashrc

#install googletest with gcc8
RUN spack install googletest+gmock~shared%gcc@8.1.0

CMD /bin/bash