FROM mfcats/splinelib:gtest

# Add current directory as working directory to docker
ADD . /code
WORKDIR /code

RUN spack repo add /code/scripts/spack-repo
RUN spack setup -v splinelib@github build_type=Debug %clang@6
RUN mkdir /code/build-clang6-debug-valgrind
WORKDIR /code/build-clang6-debug-valgrind
RUN ../spconfig.py ..

# Build and execute tests
CMD make && valgrind --track-origins=yes ./test/SplineLibTests --gtest_filter=AnIGATestSpline.*
