FROM christophsusen/gtest

# Add current directory as working directory to docker
ADD . /code
WORKDIR /code

ENV CXXFLAGS="-coverage"

RUN spack repo add /code/scripts/spack-repo
RUN spack setup -v splinelib@github build_type=Debug %gcc@7
RUN mkdir /code/build-gcc7-coverage
WORKDIR /code/build-gcc7-coverage
RUN ../spconfig.py ..

# Generate code coverage output
RUN lcov --directory . --zerocounters && \
make SplineLibTests && \
./test/SplineLibTests && \
lcov --directory . --capture --output-file coverage.info && \
lcov --remove coverage.info '/usr/*' --output-file coverage.info && \
lcov --remove coverage.info '*/.cache/*' --output-file coverage.info && \
lcov --remove coverage.info '*/CMakeFiles/*' --output-file coverage.info && \
lcov --remove coverage.info '*/external/*' --output-file coverage.info && \
lcov --remove coverage.info '*/io/executables/*' --output-file coverage.info && \
lcov --list coverage.info && \
find . -name "*.gcov" -type f -delete && \
find . -name "*.gcda" -type f -delete && \
find . -name "*.gcno" -type f -delete

# Set-up shell
SHELL ["bash", "-c"]

CMD /bin/bash <(curl -s https://codecov.io/bash)
