FROM mfcats/splinelib:spack

# Add current directory as working directory to docker
ADD . /code
WORKDIR /code

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /spack/bashrc

RUN spack repo add /code/scripts/spack-repo
RUN spack setup -v splinelib@github%gcc@7.3.0
RUN mkdir /code/build
WORKDIR /code/build
RUN ./../spconfig.py ..

# Build and execute tests
RUN cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../

# execute cpplint
CMD run-clang-tidy.py