FROM cm314/splinelib:googletest_gcc8_new2

# Add current directory as working directory to docker
ADD . /code
WORKDIR /code

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /code/bashrc2
ENV CXXFLAGS="-coverage"

# Prepare build
# RUN pip install cpplint
# RUN cpplint --recursive /code/src/*
RUN apt-get update && apt-get -y upgrade && apt-get install -y lcov

WORKDIR /code
RUN /code/.cache/spack/bin/spack repo add /code/scripts/spack-repo
RUN /code/.cache/spack/bin/spack setup -v splinelib@github%gcc@8.1.0
RUN mkdir /code/build
WORKDIR /code/build
RUN ./../spconfig.py ..

# Build and execute tests
CMD make CXXFLAGS=-coverage LDFLAGS=--coverage && ./test/SplineLibTests CXXFLAGS=--coverage LDFLAGS=--coverage