FROM cm314/splinelib:gtest3

# Add current directory as working directory to docker
ADD . /code
WORKDIR /code

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /spack/bashrc

RUN spack repo add /code/scripts/spack-repo
RUN spack setup -v splinelib@github%gcc@8 build_type=Debug
RUN mkdir /code/build
WORKDIR /code/build
RUN ./../spconfig.py ..

# Build and execute tests
CMD make && ./test/SplineLibTests
