FROM mfcats/splinelib:gcc8_dependencies

# Work in /code
WORKDIR /code

# Add current directory as working directory to docker
ADD . /code
SHELL ["bash"]

CMD ["/bin/bash", "-c", "./prepare_splinelibtests.sh"]
