# Build on top of ubuntu
FROM mfcats/splinelib:spack

# Work in /spack
WORKDIR /spack

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /spack/bashrc

# Install linter
RUN pip install cpplint

CMD /bin/bash
