FROM mfcats/splinelib:spack

# Add code directory
ADD . /spackrepo
WORKDIR /spackrepo

RUN apt-get update && apt-get install -y cmake

RUN mv ./scripts/docker/packages.yaml /root/.spack/linux/packages.yaml

# Install googletest versions
RUN spack repo add /spackrepo/scripts/spack-repo
RUN spack spec splinelib
RUN spack setup -v splinelib@github build_type=Debug %gcc@7
RUN spack setup -v splinelib@github build_type=Release %gcc@7
RUN spack setup -v splinelib@github build_type=Debug %clang@6
RUN spack setup -v splinelib@github build_type=Release %clang@6
RUN spack setup -v splinelib@github build_type=Debug %clang@5
RUN spack setup -v splinelib@github build_type=Release %clang@5
RUN spack setup -v splinelib@github build_type=Debug %gcc@8
RUN spack setup -v splinelib@github build_type=Release %gcc@8
RUN spack clean -a

CMD /bin/bash

# Add current directory as working directory to docker
ADD . /code
WORKDIR /code

RUN spack repo add /code/scripts/spack-repo
RUN spack setup -v splinelib@github build_type=Debug %clang@6
RUN mkdir /code/build-clang6-debug
WORKDIR /code/build-clang6-debug
RUN ../spconfig.py ..

# Build and execute tests
CMD make && ./test/SplineLibTests
