# Build on top of ubuntu
FROM mfcats/splinelib:spack

# Work in /spack
WORKDIR /spack

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /spack/bashrc

# Install gcc@7.3.0
RUN spack install -v gcc@7.3.0
RUN spack load gcc@7.3.0
RUN spack compiler find

CMD /bin/bash
