# Build on top of ubuntu
FROM mfcats/splinelib:spack

# Work in /code
WORKDIR /code

# Add current directory as working directory to docker
ADD . /code

# Set some common environment variables
ENV SPACK_ROOT /code/.cache/spack
ENV PATH "/code/.cache/spack/bin/:${PATH}"
ENV FORCE_UNSAFE_CONFIGURE 1

RUN spack install -v llvm

CMD /bin/bash
