FROM mfcats/splinelib:gtest_gcc7

# Add current directory as working directory to docker
ADD . /code
WORKDIR /code

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /spack/bashrc
ENV CXXFLAGS="-coverage"

RUN spack repo add /code/scripts/spack-repo
RUN spack setup -v splinelib@github%gcc@7.3.0
RUN mkdir /code/build
WORKDIR /code/build
RUN ./../spconfig.py ..

# Build and execute tests
CMD make && ./test/SplineLibTests