# Build on top of ubuntu
FROM mfcats/splinelib:spack

# Work in /spack
WORKDIR /spack

# Set-up shell
SHELL ["bash", "-c"]
ENV BASH_ENV /spack/bashrc

# Install llvm@5.0.1
RUN spack install -v llvm@5.0.1
RUN spack load llvm@5.0.1
RUN spack compiler find

CMD /bin/bash
